
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'num suma resta multiplicacion divicion palcalculadora : operacionesoperaciones : operacionoperacion : n1 op n2 n1 : palabra\n          | numeroop : simbolo\n          | palabran2 : palabra\n          | numeropalabra : palsimbolo : suma\n               | resta\n               | divicion\n               | multiplicacionnumero : num'
    
_lr_action_items = {'divicion':([2,3,5,6,8,],[-5,-15,-4,9,-10,]),'num':([0,8,9,10,11,12,13,14,15,],[3,-10,-13,-14,-7,-6,-12,-11,3,]),'multiplicacion':([2,3,5,6,8,],[-5,-15,-4,10,-10,]),'resta':([2,3,5,6,8,],[-5,-15,-4,13,-10,]),'pal':([0,2,3,5,6,8,9,10,11,12,13,14,15,],[8,-5,-15,-4,8,-10,-13,-14,-7,-6,-12,-11,8,]),'suma':([2,3,5,6,8,],[-5,-15,-4,14,-10,]),'$end':([1,3,4,7,8,16,17,18,],[-2,-15,-1,0,-10,-9,-8,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'operacion':([0,],[1,]),'numero':([0,15,],[2,16,]),'operaciones':([0,],[4,]),'palabra':([0,6,15,],[5,11,17,]),'n1':([0,],[6,]),'calculadora':([0,],[7,]),'simbolo':([6,],[12,]),'n2':([15,],[18,]),'op':([6,],[15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calculadora","S'",1,None,None,None),
  ('calculadora -> operaciones','calculadora',1,'p_calculadora','analisis_sintactico.py',2),
  ('operaciones -> operacion','operaciones',1,'p_operaciones','analisis_sintactico.py',5),
  ('operacion -> n1 op n2','operacion',3,'p_operacion','analisis_sintactico.py',8),
  ('n1 -> palabra','n1',1,'p_n1','analisis_sintactico.py',11),
  ('n1 -> numero','n1',1,'p_n1','analisis_sintactico.py',12),
  ('op -> simbolo','op',1,'p_op','analisis_sintactico.py',15),
  ('op -> palabra','op',1,'p_op','analisis_sintactico.py',16),
  ('n2 -> palabra','n2',1,'p_n2','analisis_sintactico.py',19),
  ('n2 -> numero','n2',1,'p_n2','analisis_sintactico.py',20),
  ('palabra -> pal','palabra',1,'p_palabra','analisis_sintactico.py',23),
  ('simbolo -> suma','simbolo',1,'p_simbolo','analisis_sintactico.py',26),
  ('simbolo -> resta','simbolo',1,'p_simbolo','analisis_sintactico.py',27),
  ('simbolo -> divicion','simbolo',1,'p_simbolo','analisis_sintactico.py',28),
  ('simbolo -> multiplicacion','simbolo',1,'p_simbolo','analisis_sintactico.py',29),
  ('numero -> num','numero',1,'p_numero','analisis_sintactico.py',32),
]
